custom_postgres:
  outputs:

    dev:
      dbname: destination_db
      host: host.docker.internal
      pass: some_password
      port: 5434
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
